USE [SPA_SQL]
GO
/****** Object:  Trigger [dbo].[HASH_PO_HISTORY_1.12_01]    Script Date: 02.02.2018 13:18:17 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Daniele, Salvigni>
-- Create date: <@2018>
-- Description:	<Create UID>
-- =============================================
CREATE TRIGGER [dbo].[CREATE_UPDATE_HASH_PO_HISTORY_ETL]
   ON  [dbo].[PO_HISTORY_ETL] 
   INSTEAD OF INSERT
AS 
BEGIN
	SET NOCOUNT ON;
		INSERT [dbo].[PO_HISTORY_ETL](
		[EKBE_SYSID],
		[EKBE_MANDT],
		[EKBE_EBELN],
		[EKBE_EBELP],
		[EKBE_AREWB],
		[EKBE_AREWR],
		[EKBE_AREWR_POP],
		[EKBE_AREWW],
		[EKBE_BAMNG],
		[EKBE_BEKKN],
		[EKBE_BELNR],
		[EKBE_BEWTP],
		[EKBE_BLDAT],
		[EKBE_BPMNG],
		[EKBE_BPMNG_POP],
		[EKBE_BPWEB],
		[EKBE_BPWES],
		[EKBE_BUDAT],
		[EKBE_BUZEI],
		[EKBE_BWART],
		[EKBE_BWTAR],
		[EKBE_CHARG],
		[EKBE_CPUDT],
		[EKBE_CPUTM],
		[EKBE_DMBTR],
		[EKBE_DMBTR_POP],
		[EKBE_ELIKZ],
		[EKBE_EMATN],
		[EKBE_ERNAM],
		[EKBE_ET_UPD],
		[EKBE_ETENS],
		[EKBE_EVERE],
		[EKBE_GJAHR],
		[EKBE_GRUND],
		[EKBE_HSWAE],
		[EKBE_INTROW],
		[EKBE_KNUMV],
		[EKBE_KUDIF],
		[EKBE_LEMIN],
		[EKBE_LFBNR],
		[EKBE_LFGJA],
		[EKBE_LFPOS],
		[EKBE_LSMEH],
		[EKBE_LSMNG],
		[EKBE_MATNR],
		[EKBE_MENGE],
		[EKBE_MENGE_POP],
		[EKBE_MWSKZ],
		[EKBE_PACKNO],
		[EKBE_REEWR],
		[EKBE_REFWR],
		[EKBE_RETAMT_FC],
		[EKBE_RETAMT_LC],
		[EKBE_RETAMTP_FC],
		[EKBE_RETAMTP_LC],
		[EKBE_REWRB],
		[EKBE_SAPRL],
		[EKBE_SHKZG],
		[EKBE_SRVPOS],
		[EKBE_VGABE],
		[EKBE_WAERS],
		[EKBE_WEORA],
		[EKBE_WERKS],
		[EKBE_WESBB],
		[EKBE_WESBS],
		[EKBE_WKURS],
		[EKBE_WRBTR],
		[EKBE_WRBTR_POP],
		[EKBE_XBLNR],
		[EKBE_XMACC],
		[EKBE_XUNPL],
		[EKBE_XWOFF],
		[EKBE_XWSBR],
		[EKBE_ZEKKN],
		[EKBE_ERUSERNAME],
		[EKBE_AEUSERNAME],
		[EKBE_UDATE],
		[EKBE_DATUM],
		[HASH_PO_HISTORY],
		[HASH_PO_ITEM],
		[HASH_PO_CONFIRMATION]
		)
			SELECT 
				i.[EKBE_SYSID],
				i.[EKBE_MANDT],
				[dbo].[add_0](10,REPLACE(i.[EKBE_EBELN] ,'"','')),
				[dbo].[add_0](5,REPLACE(i.[EKBE_EBELP] ,'"','')),
				i.[EKBE_AREWB],
				i.[EKBE_AREWR],
				i.[EKBE_AREWR_POP],
				i.[EKBE_AREWW],
				i.[EKBE_BAMNG],
				i.[EKBE_BEKKN],
				[dbo].[add_0](10,REPLACE(i.[EKBE_BELNR] ,'"','')),
				i.[EKBE_BEWTP],
				i.[EKBE_BLDAT],
				i.[EKBE_BPMNG],
				i.[EKBE_BPMNG_POP],
				i.[EKBE_BPWEB],
				i.[EKBE_BPWES],
				i.[EKBE_BUDAT],
				[dbo].[add_0](3,REPLACE(i.[EKBE_BUZEI] ,'"','')),
				i.[EKBE_BWART],
				i.[EKBE_BWTAR],
				i.[EKBE_CHARG],
				i.[EKBE_CPUDT],
				i.[EKBE_CPUTM],
				i.[EKBE_DMBTR],
				i.[EKBE_DMBTR_POP],
				i.[EKBE_ELIKZ],
				i.[EKBE_EMATN],
				i.[EKBE_ERNAM],
				i.[EKBE_ET_UPD],
				[dbo].[add_0](4,REPLACE(i.[EKBE_ETENS] ,'"','')),
				i.[EKBE_EVERE],
				i.[EKBE_GJAHR],
				i.[EKBE_GRUND],
				i.[EKBE_HSWAE],
				i.[EKBE_INTROW],
				i.[EKBE_KNUMV],
				i.[EKBE_KUDIF],
				i.[EKBE_LEMIN],
				i.[EKBE_LFBNR],
				i.[EKBE_LFGJA],
				i.[EKBE_LFPOS],
				i.[EKBE_LSMEH],
				i.[EKBE_LSMNG],
				i.[EKBE_MATNR],
				i.[EKBE_MENGE],
				i.[EKBE_MENGE_POP],
				i.[EKBE_MWSKZ],
				i.[EKBE_PACKNO],
				i.[EKBE_REEWR],
				i.[EKBE_REFWR],
				i.[EKBE_RETAMT_FC],
				i.[EKBE_RETAMT_LC],
				i.[EKBE_RETAMTP_FC],
				i.[EKBE_RETAMTP_LC],
				i.[EKBE_REWRB],
				i.[EKBE_SAPRL],
				i.[EKBE_SHKZG],
				i.[EKBE_SRVPOS],
				i.[EKBE_VGABE],
				i.[EKBE_WAERS],
				i.[EKBE_WEORA],
				i.[EKBE_WERKS],
				i.[EKBE_WESBB],
				i.[EKBE_WESBS],
				i.[EKBE_WKURS],
				i.[EKBE_WRBTR],
				i.[EKBE_WRBTR_POP],
				i.[EKBE_XBLNR],
				i.[EKBE_XMACC],
				i.[EKBE_XUNPL],
				i.[EKBE_XWOFF],
				i.[EKBE_XWSBR],
				[dbo].[add_0](2,REPLACE(i.[EKBE_ZEKKN] ,'"','')),
				i.[EKBE_ERUSERNAME],
				i.[EKBE_AEUSERNAME],
				i.[EKBE_UDATE],
				i.[EKBE_DATUM],
				HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[EKBE_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[EKBE_MANDT],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[EKBE_EBELN] ,'"','')),' ',''),REPLACE([dbo].[add_0](5,REPLACE(i.[EKBE_EBELP] ,'"','')),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[EKBE_BELNR] ,'"','')),' ',''),REPLACE([dbo].[add_0](4,REPLACE(i.[EKBE_BUZEI] ,'"','')),' ',''),REPLACE(REPLACE(i.[EKBE_GJAHR],'"',''),' ',''),REPLACE(REPLACE(i.[EKBE_VGABE],'"',''),' ',''),REPLACE([dbo].[add_0](2,REPLACE(i.[EKBE_ZEKKN] ,'"','')),' ',''))) as [HASH_PO_HISTORY],
				HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[EKBE_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[EKBE_MANDT],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[EKBE_EBELN] ,'"','')),' ',''),REPLACE([dbo].[add_0](5,REPLACE(i.[EKBE_EBELP] ,'"','')),' ',''))) as [HASH_PO_ITEM],
				HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[EKBE_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[EKBE_MANDT],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[EKBE_EBELN] ,'"','')),' ',''),REPLACE([dbo].[add_0](5,REPLACE(i.[EKBE_EBELP] ,'"','')),' ',''),REPLACE([dbo].[add_0](4,REPLACE(i.[EKBE_ETENS],'"','')),' ',''))) as [HASH_PO_CONFIRMATION]
				FROM 
				inserted as i;
END


