USE [SPA_SQL]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Daniele, Salvigni>
-- Create date: <@2018>
-- Description:	<Create UID>
-- =============================================
CREATE TRIGGER [dbo].[CREATE_UPDATE_HASH_INV_ITEM_ETL]
   ON  [dbo].[INV_ITEM_ETL] 
   INSTEAD OF INSERT
AS 
BEGIN
	SET NOCOUNT ON;
		INSERT [dbo].[INV_ITEM_ETL](
		[BSEG_SYSID],
		[BSEG_MANDT],
		[BSEG_GJAHR],
		[BSEG_BELNR],
		[BSEG_BUZEI],
		[BSEG_BUZID],
		[BSEG_BUKRS],
		[BSEG_MENGE],
		[BSEG_MEINS],
		[BSEG_WRBTR],
		[BSEG_DMBTR],
		[BSEG_AMOUNTEUR],
		[BSEG_LONGTEXT],
		[BSEG_SGTXT],
		[BSEG_MATNR],
		[BSEG_LIFNR],
		[BSEG_HKONT],
		[BSEG_SAKNR],
		[BSEG_WERKS],
		[BSEG_KOSTL],
		[BSEG_VERTN],
		[BSEG_EBELN],
		[BSEG_EBELP],
		[BSEG_ZEKKN],
		[BSEG_AUGDT],
		[BSEG_ZUONR],
		[BSEG_ZTERM],
		[BSEG_BSCHL],
		[BSEG_KOART],
		[BSEG_SHKZG],
		[BSEG_MWSKZ],
		[BSEG_MWART],
		[BSEG_KTOSL],
		[BSEG_BEWAR],
		[BSEG_XUMSW],
		[BSEG_POSID],
		[BSEG_NPLNR],
		[BSEG_ZZBKZ],
		[BSEG_PRCTR],
		[BSEG_AUFNR],
		[BSEG_VBEL2],
		[BSEG_POSN2],
		[BSEG_AUGGJ],
		[BSEG_AUGBL],
		[BSEG_AGZEI],
		[BSEG_ERUSERNAME],
		[BSEG_UDATE],
		[BSEG_AEUSERNAME],
		[BSEG_UDATE_2],
		[BSEG_DATUM],
		[BSEG_BUDAT],
		[BSEG_PROJK],
		[BSEG_ERDATE],
		[HASH_INV_HEADER_UNIQUE],
		[HASH_INV_HEADER],
		[HASH_INV_ITEM_UNIQUE],
		[HASH_INV_ITEM],
		[HASH_PO_ITEM],
		[HASH_SUPPLIER_LFA1],
		[HASH_SUPPLIER_LFB1],
		[HASH_MD_ACCOUNT],
		[HASH_INV_FINANCE]
		)
			SELECT
					i.[BSEG_SYSID],
					i.[BSEG_MANDT],
					i.[BSEG_GJAHR],
					[dbo].[add_0](10,REPLACE(i.[BSEG_BELNR],'"','')),
					[dbo].[add_0](3,REPLACE(i.[BSEG_BUZEI],'"','')),
					i.[BSEG_BUZID],
					[dbo].[add_0](4,REPLACE(i.[BSEG_BUKRS],'"','')),
					i.[BSEG_MENGE],
					i.[BSEG_MEINS],
					i.[BSEG_WRBTR],
					i.[BSEG_DMBTR],
					i.[BSEG_AMOUNTEUR],
					i.[BSEG_LONGTEXT],
					i.[BSEG_SGTXT],
					i.[BSEG_MATNR],
					[dbo].[rem_0](REPLACE(i.[BSEG_LIFNR],'"','')),
					i.[BSEG_HKONT],
					[dbo].[add_0](10,REPLACE(i.[BSEG_SAKNR],'"','')),
					i.[BSEG_WERKS],
					i.[BSEG_KOSTL],
					[dbo].[add_0](10,REPLACE(i.[BSEG_VERTN],'"','')),
					[dbo].[add_0](10,REPLACE(i.[BSEG_EBELN],'"','')),
					[dbo].[add_0](10,REPLACE(i.[BSEG_EBELP],'"','')),
					[dbo].[add_0](2,REPLACE(i.[BSEG_ZEKKN],'"','')),
					i.[BSEG_AUGDT],
					i.[BSEG_ZUONR],
					i.[BSEG_ZTERM],
					i.[BSEG_BSCHL],
					i.[BSEG_KOART],
					i.[BSEG_SHKZG],
					i.[BSEG_MWSKZ],
					i.[BSEG_MWART],
					i.[BSEG_KTOSL],
					i.[BSEG_BEWAR],
					i.[BSEG_XUMSW],
					i.[BSEG_POSID],
					[dbo].[add_0](12,REPLACE(i.[BSEG_NPLNR],'"','')),
					i.[BSEG_ZZBKZ],
					i.[BSEG_PRCTR],
					i.[BSEG_AUFNR],
					i.[BSEG_VBEL2],
					i.[BSEG_POSN2],
					i.[BSEG_AUGGJ],
					i.[BSEG_AUGBL],
					i.[BSEG_AGZEI],
					i.[BSEG_ERUSERNAME],
					i.[BSEG_UDATE],
					i.[BSEG_AEUSERNAME],
					i.[BSEG_UDATE_2],
					i.[BSEG_DATUM],
					i.[BSEG_BUDAT],
					i.[BSEG_PROJK],
					i.[BSEG_ERDATE],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_GJAHR],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[BSEG_BELNR],'"','')),' ',''),REPLACE([dbo].[add_0](4,REPLACE(i.[BSEG_BUKRS],'"','')),' ',''))) as [HASH_INV_HEADER_UNIQUE],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_GJAHR],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[BSEG_BELNR],'"','')),' ',''))) as [HASH_INV_HEADER],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_GJAHR],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[BSEG_BELNR],'"','')),' ',''),REPLACE([dbo].[add_0](3,REPLACE(i.[BSEG_BUZEI],'"','')),' ',''),REPLACE([dbo].[add_0](4,REPLACE(i.[BSEG_BUKRS],'"','')),' ',''))) as [HASH_INV_ITEM_UNIQUE],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_GJAHR],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[BSEG_BELNR],'"','')),' ',''),REPLACE([dbo].[add_0](3,REPLACE(i.[BSEG_BUZEI],'"','')),' ',''))) as [HASH_INV_ITEM],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[BSEG_EBELN],'"','')),' ',''),REPLACE([dbo].[add_0](5,REPLACE(i.[BSEG_EBELP],'"','')),' ',''))) as [HASH_PO_ITEM],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE([dbo].[rem_0](REPLACE(i.[BSEG_LIFNR],'"','')),' ',''))) as [HASH_SUPPLIER_LFA1],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE([dbo].[rem_0](REPLACE(i.[BSEG_LIFNR],'"','')),' ',''),REPLACE([dbo].[add_0](4,REPLACE(i.[BSEG_BUKRS],'"','')),' ',''))) as [HASH_SUPPLIER_LFB1],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[BSEG_SAKNR],'"','')),' ',''))) as [HASH_MD_ACCOUNT],
					HASHBYTES('MD5',CONCAT(REPLACE(REPLACE(i.[BSEG_SYSID],'"',''),' ',''),REPLACE(REPLACE(i.[BSEG_MANDT],'"',''),' ',''),REPLACE([dbo].[add_0](10,REPLACE(i.[BSEG_BELNR],'"','')),' ',''),REPLACE([dbo].[add_0](3,REPLACE(i.[BSEG_BUZEI],'"','')),' ',''))) as [HASH_INV_FINANCE]					
				FROM 
				inserted as i;
END


